from __future__ import annotations

import json


def render_fresh_app(token: str) -> str:
    token_json = json.dumps(token)
    return r'''<!doctype html>
<html lang="vi">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cài mới WordPress</title>
<style>
:root{--bg:#f5f6f8;--panel:#fff;--text:#1d2735;--muted:#64748b;--line:#dbe3ed;--soft:#f8fafc;--brand:#2563eb;--brand-dark:#1d4ed8;--green:#087443;--green-bg:#ecfdf3;--yellow:#946000;--yellow-bg:#fff8e6;--red:#b42335;--red-bg:#fff1f2;--focus:rgba(37,99,235,.25);--radius:9px}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font:14px/1.45 "Segoe UI",Arial,sans-serif;background:var(--bg);color:var(--text)}button,input,select{font:inherit}button{cursor:pointer;touch-action:manipulation}.page{width:100%;max-width:1800px;margin:auto;padding:28px 30px 40px}.head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px}.head h1{margin:0;font-size:25px;line-height:1.2}.head p{margin:5px 0 0;color:var(--muted)}
.summary{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr)) minmax(210px,1.1fr);margin-bottom:18px;background:#fff;border:1px solid var(--line);border-radius:var(--radius);overflow:hidden}.metric,.syncbox{min-height:74px;padding:12px 16px;display:flex;justify-content:center;flex-direction:column;border-right:1px solid var(--line)}.summary>:last-child{border-right:0}.metric b{font-size:21px;line-height:1.1}.metric span{margin-top:5px;color:var(--muted)}.syncbox{align-items:center;flex-direction:row;gap:8px;color:var(--green);font-weight:650}.dot{width:9px;height:9px;border-radius:50%;background:#22c55e;box-shadow:0 0 0 3px #dcfce7}
.listtoolbar{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:10px}.listtoolbar h2{margin:0;font-size:18px}.listtoolbar p{margin:4px 0 0;color:var(--muted)}.actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap}.search{width:280px;height:36px;padding:7px 11px;border:1px solid var(--line);border-radius:7px;background:#fff}.btn{height:36px;padding:7px 13px;display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid var(--line);border-radius:7px;background:#fff;color:#334155;font-weight:650}.btn:hover{background:#f8fafc}.btn.primary{color:#fff;background:var(--brand);border-color:var(--brand)}.btn.primary:hover{background:var(--brand-dark)}.btn.danger{color:var(--red);border-color:#fecaca;background:#fff}.btn.danger:hover{background:var(--red-bg)}.btn:disabled{opacity:.5;cursor:not-allowed}.btn:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid var(--focus);outline-offset:2px}
.panel{background:transparent}.list{display:grid;gap:9px}.row{overflow:hidden;border:1px solid var(--line);border-radius:var(--radius);background:#fff}.rowmain{min-height:84px;padding:13px 14px;display:grid;grid-template-columns:minmax(240px,1.45fr) 145px minmax(200px,1fr) 190px 62px;gap:14px;align-items:center;cursor:pointer}.rowmain:hover{background:#fafcff}.identity{min-width:0;display:flex;gap:11px;align-items:center}.wp{width:36px;height:36px;display:grid;place-items:center;flex:0 0 auto;border-radius:7px;color:#1d4ed8;background:#eff6ff;font-weight:800}.identity strong,.identity span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.identity span,.steptext{color:var(--muted)}.badge{width:max-content;padding:5px 8px;border-radius:5px;font-weight:700}.badge.ready{color:#1d4ed8;background:#eff6ff}.badge.running{color:var(--yellow);background:var(--yellow-bg)}.badge.success{color:var(--green);background:var(--green-bg)}.badge.error{color:var(--red);background:var(--red-bg)}.progresswrap{display:flex;align-items:center;gap:9px}.progressline{height:7px;flex:1;overflow:hidden;border-radius:6px;background:#e8edf3}.progressline span{display:block;height:100%;background:var(--brand);transition:width .2s}.progressnum{width:38px;text-align:right;color:var(--muted);font-variant-numeric:tabular-nums}.openbtn{pointer-events:none}.errorbox{margin:0 14px 12px 61px;padding:9px 11px;border:1px solid #fecaca;border-radius:7px;color:var(--red);background:var(--red-bg);overflow-wrap:anywhere}.empty{padding:58px 20px;text-align:center;color:var(--muted)}.empty strong{display:block;margin-bottom:5px;color:var(--text);font-size:17px}
.steptext{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.overlay{position:fixed;inset:0;z-index:40;display:none;background:rgba(15,23,42,.46)}.overlay.show{display:block}.modal{position:fixed;inset:0;z-index:50;display:none;align-items:center;justify-content:center;padding:18px}.modal.show{display:flex}.modalbox{width:min(650px,97vw);max-height:94vh;overflow:auto;background:#fff;border:1px solid var(--line);border-radius:10px;box-shadow:0 24px 65px rgba(15,23,42,.2)}.modalbox.detail{width:min(760px,97vw)}.modalhead{position:sticky;top:0;z-index:2;padding:16px 18px;display:flex;align-items:center;justify-content:space-between;gap:14px;background:#fff;border-bottom:1px solid var(--line)}.modalhead h2{margin:0;font-size:20px}.modalhead p{margin:3px 0 0;color:var(--muted)}.close{width:36px;height:36px;border:1px solid var(--line);border-radius:7px;background:#fff;font-size:20px}.modalbody{padding:16px 18px}.section{margin-bottom:16px}.section:last-child{margin:0}.sectiontitle{margin:0 0 9px;font-size:15px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.field{display:grid;gap:5px}.field.full{grid-column:1/-1}.field label{font-weight:650}.field input,.field select{width:100%;height:40px;padding:7px 10px;border:1px solid var(--line);border-radius:7px;background:#fff}.fieldaction{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.workerstatus{min-height:22px;margin:6px 0 0;color:var(--muted)}.advanced{margin:14px 0;border:1px solid var(--line);border-radius:8px;background:var(--soft)}.advanced summary{padding:10px 12px;font-weight:700;cursor:pointer}.advanced .grid{padding:2px 12px 12px}.confirm{padding:10px 11px;display:flex;align-items:flex-start;gap:9px;border:1px solid #f1c6c9;border-radius:7px;color:#7f1d2d;background:var(--red-bg);font-weight:650}.confirm input{width:18px;height:18px;margin:1px 0 0;flex:0 0 auto}.packagebar{margin:14px 0 10px;display:flex;gap:7px;flex-wrap:wrap}.package{padding:5px 8px;border-radius:5px;color:#1d4ed8;background:#eaf2ff;font-weight:700}.modalactions{position:sticky;bottom:0;padding:11px 18px;display:flex;justify-content:flex-end;gap:8px;background:#fff;border-top:1px solid var(--line)}
.jobbox{padding:12px;border:1px solid var(--line);border-radius:8px;background:#fbfcfe}.jobtop{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.jobtop h3{margin:0;font-size:16px}.jobtop p{margin:4px 0 0;color:var(--muted);overflow-wrap:anywhere}.jobmetrics{display:grid;grid-template-columns:repeat(3,1fr);margin:12px 0;border:1px solid var(--line);border-radius:7px;overflow:hidden}.jobmetric{padding:9px 10px;border-right:1px solid var(--line)}.jobmetric:last-child{border:0}.jobmetric span,.jobmetric b{display:block}.jobmetric span{color:var(--muted)}.jobmetric b{margin-top:3px}.currentfile{margin-top:8px;color:#475569;overflow-wrap:anywhere}.loglist{max-height:250px;overflow:auto;border:1px solid var(--line);border-radius:7px;background:#fff}.logitem{padding:8px 10px;border-bottom:1px solid #edf1f5;font-family:Consolas,monospace;overflow-wrap:anywhere}.logitem:last-child{border:0}.history{display:grid;border:1px solid var(--line);border-radius:7px;overflow:hidden}.historyitem{min-height:46px;padding:8px 10px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:9px;border-bottom:1px solid #edf1f5}.historyitem:last-child{border:0}.historyitem time{color:var(--muted);white-space:nowrap}.historydot{width:8px;height:8px;border-radius:50%;background:#3b82f6}.historydot.success{background:#16a34a}.historydot.error{background:#dc2626}.detailactions{display:flex;gap:8px;flex-wrap:wrap}.toast{position:fixed;right:22px;bottom:22px;z-index:90;max-width:520px;padding:11px 14px;border-radius:7px;color:#fff;background:#253044;opacity:0;transform:translateY(80px);transition:.18s}.toast.show{opacity:1;transform:none}.toast.error{background:#9f2937}
@media(max-width:1000px){.rowmain{grid-template-columns:1fr auto}.rowmain>.steptext,.rowmain>.progresswrap{grid-column:1}.rowmain>.openbtn{grid-row:1;grid-column:2}.summary{grid-template-columns:repeat(2,1fr)}.summary>:nth-child(even){border-right:0}.syncbox{grid-column:1/-1;border-top:1px solid var(--line)}}@media(max-width:700px){.page{padding:18px 12px}.listtoolbar{align-items:stretch;flex-direction:column}.actions{justify-content:flex-start}.search{width:100%}.grid{grid-template-columns:1fr}.field.full{grid-column:auto}.summary{grid-template-columns:1fr 1fr}.jobmetrics{grid-template-columns:1fr}.jobmetric{border-right:0;border-bottom:1px solid var(--line)}.historyitem{grid-template-columns:auto 1fr}.historyitem time{grid-column:2}.errorbox{margin-left:14px}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}
</style>
</head>
<body>
<main class="page">
  <section class="summary"><div class="metric"><b id="total">0</b><span>Tổng website</span></div><div class="metric"><b id="done">0</b><span>Đã cài</span></div><div class="metric"><b id="running">0</b><span>Đang chạy</span></div><div class="metric"><b id="issues">0</b><span>Cần xử lý</span></div><div class="syncbox"><i class="dot"></i><span id="syncText">Đang đồng bộ</span></div></section>
  <section class="listtoolbar"><div><h2>Danh sách website</h2><p>Chọn website để xem tiến trình.</p></div><div class="actions"><input id="search" class="search" type="search" aria-label="Tìm website" placeholder="Tìm domain" oninput="render()"><button class="btn" type="button" onclick="refresh()">Làm mới</button><button class="btn primary" type="button" onclick="openCreate()">Tạo website</button></div></section>
  <section class="panel"><div id="list" class="list"></div></section>
</main>
<div id="overlay" class="overlay" onclick="closeModal()"></div>
<section id="createModal" class="modal" role="dialog" aria-modal="true" aria-labelledby="createTitle"><form id="createForm" class="modalbox" onsubmit="submitCreate(event)"><header class="modalhead"><h2 id="createTitle">Tạo website mới</h2><button class="close" type="button" aria-label="Đóng" onclick="closeModal()">×</button></header><div class="modalbody">
  <div class="grid"><div class="field full"><label for="domain">Domain</label><input id="domain" name="domain" required placeholder="tongkhokhoathongminh.com" oninput="domainChanged()"></div><div class="field"><label for="username">Tài khoản FTP</label><input id="username" name="username" required autocomplete="off" oninput="usernameChanged()"></div><div class="field"><label for="password">Mật khẩu FTP & quản trị</label><input id="password" name="password" type="password" minlength="12" required autocomplete="new-password"></div><div class="field"><label for="dbName">Tên database</label><input id="dbName" name="dbName" required autocomplete="off" oninput="markDbManual('name')"></div><div class="field"><label for="dbUser">Tài khoản database</label><input id="dbUser" name="dbUser" required autocomplete="off" oninput="markDbManual('user')"></div><div class="field"><label for="adminUser">Tài khoản quản trị</label><input id="adminUser" name="adminUser" value="admin" required autocomplete="off"></div></div>
  <input id="siteTitle" name="siteTitle" type="hidden"><input id="siteUrl" name="siteUrl" type="hidden"><input id="adminEmail" name="adminEmail" type="hidden">
  <details class="advanced"><summary>Cấu hình nâng cao</summary><div class="grid"><div class="field"><label for="host">Máy chủ FTP</label><input id="host" name="host" required></div><div class="field"><label for="protocol">Giao thức</label><select id="protocol" name="protocol"><option value="ftp">FTP</option><option value="ftps">FTPS</option></select></div><div class="field"><label for="port">Cổng</label><input id="port" name="port" type="number" min="1" max="65535" value="21" required></div><div class="field"><label for="workers">Luồng FTP</label><div class="fieldaction"><select id="workers" name="workers"><option>4</option><option selected>8</option><option>12</option><option>16</option></select><button id="probeWorkersButton" class="btn" type="button" onclick="probeWorkers()">Đo tối đa</button></div><div id="workerAdvice" class="workerstatus"></div></div><div class="field"><label for="dbHost">Database host</label><input id="dbHost" name="dbHost" value="localhost" required></div><div class="field full"><label for="remotePath">Thư mục website</label><input id="remotePath" name="remotePath" required></div><div class="field"><label for="tablePrefix">Tiền tố bảng</label><input id="tablePrefix" name="tablePrefix" value="wp_" required></div></div></details>
  <div class="packagebar"><span class="package">Bricks 2.3.10</span><span class="package">Bricks Child</span><span class="package">Duy Anh Web Pro 1.2.3</span></div><label class="confirm" for="clearRemote"><input id="clearRemote" name="clearRemote" type="checkbox" value="true" required checked><span>Xóa sạch nội dung cũ trong thư mục website trước khi cài.</span></label>
  </div><footer class="modalactions"><button class="btn" type="button" onclick="closeModal()">Huỷ</button><button id="createButton" class="btn primary" type="submit">Lưu và cài ngay</button></footer></form></section>
<section id="detailModal" class="modal" role="dialog" aria-modal="true" aria-labelledby="detailTitle"><div class="modalbox detail"><header class="modalhead"><div><h2 id="detailTitle">Chi tiết website</h2><p id="detailMeta"></p></div><button class="close" type="button" aria-label="Đóng" onclick="closeModal()">×</button></header><div id="detailBody" class="modalbody"></div><footer class="modalactions"><button class="btn" type="button" onclick="closeModal()">Đóng</button></footer></div></section>
<div id="toast" class="toast" role="status" aria-live="polite"></div>
<script>
const TOKEN=''' + token_json + r''';let sites=[],poll=null,editingName='',detailName='',autoDbName=true,autoDbUser=true;
const q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),options.timeout||20000);try{const response=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-WPClean-Token':TOKEN,...options.headers},signal:controller.signal}),data=await response.json();if(!response.ok)throw new Error(data.error||data.message||'Thao tác chưa hoàn tất');return data}finally{clearTimeout(timer)}}
function toast(message,error=false){const el=q('#toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(window._toastTimer);window._toastTimer=setTimeout(()=>el.className='toast',3800)}
function statusLabel(status){return status==='success'?'Đã cài':status==='running'?'Đang cài':status==='error'?'Cần xử lý':'Sẵn sàng'}
function dateText(value){if(!value)return '—';try{return new Date(value).toLocaleString('vi-VN',{hour12:false})}catch{return value}}
function formatDuration(value){const n=Math.max(0,Number(value||0)),m=Math.floor(n/60),s=Math.floor(n%60);return m?m+' phút '+s+' giây':s+' giây'}
function formatBytes(value){let n=Math.max(0,Number(value||0));if(n<1024)return Math.round(n)+' B';const units=['KB','MB','GB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<units.length-1);return n.toFixed(n>=10?1:2)+' '+units[i]}
async function refresh(){try{const data=await api('/api/fresh-installs');sites=data.installs||[];render();if(detailName)renderDetail();q('#syncText').textContent='Đã đồng bộ '+new Date().toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',second:'2-digit'});const active=!!detailName||sites.some(s=>s.status==='running'||s.job?.status==='running');clearTimeout(poll);if(active)poll=setTimeout(refresh,1200)}catch(e){clearTimeout(poll);if(detailName||sites.some(s=>s.status==='running'||s.job?.status==='running'))poll=setTimeout(refresh,2000);toast(e.message,true)}}
function render(){const term=q('#search').value.trim().toLowerCase(),filtered=sites.filter(s=>(s.name+' '+s.domain).toLowerCase().includes(term));q('#total').textContent=sites.length;q('#done').textContent=sites.filter(s=>s.status==='success').length;q('#running').textContent=sites.filter(s=>s.status==='running').length;q('#issues').textContent=sites.filter(s=>s.status==='error').length;q('#list').innerHTML=filtered.length?filtered.map(rowHtml).join(''):'<div class="empty"><strong>Chưa có website</strong>Bấm Tạo website để bắt đầu.</div>'}
function rowHtml(s){const j=s.job||{},running=s.status==='running'||j.status==='running',pc=Math.max(0,Math.min(100,Number(j.percent||(s.status==='success'?100:0)))),encoded=encodeURIComponent(s.name),step=j.message||s.lastError||statusLabel(s.status);return `<article class="row"><div class="rowmain" role="button" tabindex="0" onclick="showDetail('${encoded}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();showDetail('${encoded}')}"><div class="identity"><span class="wp">WP</span><div><strong>${esc(s.domain)}</strong><span>${esc(s.connection?.protocol?.toUpperCase()||'FTP')} · ${esc(s.connection?.remotePath||'')}</span></div></div><span class="badge ${esc(s.status||'ready')}">${statusLabel(s.status)}</span><span class="steptext">${esc(step)}</span><div class="progresswrap"><div class="progressline"><span style="width:${pc}%"></span></div><span class="progressnum">${pc}%</span></div><span class="btn openbtn">Mở</span></div>${s.lastError&&!running?`<div class="errorbox"><strong>Chưa hoàn tất:</strong> ${esc(s.lastError)}</div>`:''}</article>`}
function setFormValue(id,value){const el=q('#'+id);if(el)el.value=value??''}
function dbDefaults(username){return {name:username?username+'_db':'',user:username?username+'_user':''}}
function prepareForm(s=null){const form=q('#createForm');form.reset();editingName=s?.name||'';const resetDatabase=!!s&&/access denied|database từ chối/i.test(String(s.lastError||''));autoDbName=!s||resetDatabase;autoDbUser=!s||resetDatabase;q('#createTitle').textContent=s?'Sửa website':'Tạo website mới';q('#createButton').textContent=s?'Lưu và thử lại':'Lưu và cài ngay';q('#domain').readOnly=!!s;q('#workerAdvice').textContent='';q('#password').required=!s;setFormValue('port',s?.connection?.port||21);setFormValue('workers',s?.connection?.workers||8);setFormValue('dbHost',s?.database?.host||'localhost');setFormValue('tablePrefix',s?.database?.tablePrefix||'wp_');setFormValue('adminUser',s?.admin?.username||'admin');q('#clearRemote').checked=s?.clearRemote!==false;if(!s)return;setFormValue('domain',s.domain);setFormValue('siteTitle',s.admin?.siteTitle);setFormValue('siteUrl',s.siteUrl);setFormValue('host',s.connection?.host);setFormValue('username',s.connection?.username);setFormValue('protocol',s.connection?.protocol||'ftp');setFormValue('remotePath',s.connection?.remotePath);const defaults=dbDefaults(s.connection?.username||'');setFormValue('dbName',resetDatabase?defaults.name:s.database?.name);setFormValue('dbUser',resetDatabase?defaults.user:s.database?.user);setFormValue('adminEmail',s.admin?.email);if(resetDatabase)q('#workerAdvice').textContent='Đã đặt lại database theo tài khoản FTP.'}
function showCreateForm(){detailName='';q('#overlay').className='overlay show';q('#createModal').className='modal show';setTimeout(()=>q(editingName?'#username':'#domain').focus(),40)}
function openCreate(){prepareForm();showCreateForm()}
function editSite(encoded){const name=decodeURIComponent(encoded),s=sites.find(item=>item.name===name);if(!s)return;prepareForm(s);showCreateForm()}
function closeModal(){detailName='';q('#overlay').className='overlay';q('#createModal').className='modal';q('#detailModal').className='modal'}
function domainChanged(){const d=q('#domain').value.trim().toLowerCase().replace(/^https?:\/\//,'').split('/')[0].replace(/\.$/,'');setFormValue('siteTitle',d);setFormValue('siteUrl',d?'https://'+d:'');setFormValue('host',d);setFormValue('remotePath',d?'/domains/'+d+'/public_html':'');setFormValue('adminEmail',d?'admin@'+d:'')}
function markDbManual(kind){if(kind==='name')autoDbName=false;if(kind==='user')autoDbUser=false}
function usernameChanged(){const value=q('#username').value,defaults=dbDefaults(value);if(autoDbName)setFormValue('dbName',defaults.name);if(autoDbUser)setFormValue('dbUser',defaults.user)}
async function probeWorkers(){const button=q('#probeWorkersButton'),data=Object.fromEntries(new FormData(q('#createForm')).entries());data.port=Number(data.port||21);data.passive=true;data.profileName=editingName;button.disabled=true;button.textContent='Đang đo…';q('#workerAdvice').textContent='Đang kiểm tra kết nối…';try{const result=await api('/api/fresh-installs/probe-workers',{method:'POST',body:JSON.stringify(data),timeout:120000}),workers=String(result.suggestedWorkers||1),select=q('#workers');if(![...select.options].some(option=>option.value===workers))select.add(new Option(workers,workers));select.value=workers;q('#workerAdvice').textContent='Đã áp dụng '+workers+' luồng FTP.'}catch(e){q('#workerAdvice').textContent=e.message;toast(e.message,true)}finally{button.disabled=false;button.textContent='Đo tối đa'}}
async function submitCreate(event){event.preventDefault();const button=q('#createButton'),wasEditing=!!editingName,data=Object.fromEntries(new FormData(event.target).entries()),endpoint=wasEditing?'/api/fresh-installs/'+encodeURIComponent(editingName):'/api/fresh-installs';data.port=Number(data.port||21);data.workers=Number(data.workers||8);data.passive=true;data.clearRemote=q('#clearRemote').checked;data.dbPassword=data.password;data.adminPassword=data.password;button.disabled=true;button.textContent='Đang lưu…';try{const site=await api(endpoint,{method:'POST',body:JSON.stringify(data)});closeModal();await api('/api/fresh-installs/'+encodeURIComponent(site.name)+'/start',{method:'POST',body:'{}'});toast((wasEditing?'Đã cập nhật và thử lại ':'Đã bắt đầu cài ')+site.domain);editingName='';await refresh()}catch(e){toast(e.message,true)}finally{button.disabled=false;button.textContent=wasEditing?'Lưu và thử lại':'Lưu và cài ngay'}}
async function testSite(encoded){const name=decodeURIComponent(encoded);try{toast('Đang kiểm tra FTP…');const d=await api('/api/fresh-installs/'+encodeURIComponent(name)+'/test',{method:'POST',body:'{}',timeout:60000});toast(d.empty?'FTP sẵn sàng':d.willDelete?'FTP sẵn sàng; sẽ dọn '+d.blockingEntries.length+' mục':'FTP sẵn sàng; cần xác nhận dọn nội dung');await refresh()}catch(e){toast(e.message,true)}}
async function installSite(encoded){const name=decodeURIComponent(encoded),site=sites.find(item=>item.name===name);if(site&&!site.clearRemote){editSite(encoded);toast('Xác nhận dọn nội dung hosting');return}try{closeModal();await api('/api/fresh-installs/'+encodeURIComponent(name)+'/start',{method:'POST',body:'{}'});toast('Đã bắt đầu cài WordPress');await refresh()}catch(e){toast(e.message,true)}}
async function deleteSite(encoded){const name=decodeURIComponent(encoded),site=sites.find(item=>item.name===name);if(!site)return;const confirmation=prompt('Nhập '+site.domain+' để xóa khỏi OneClick.\nSource và database trên hosting vẫn được giữ nguyên.','');if(confirmation===null)return;try{await api('/api/fresh-installs/'+encodeURIComponent(name)+'/delete',{method:'POST',body:JSON.stringify({confirmation})});closeModal();toast('Đã xóa '+site.domain+' khỏi OneClick');await refresh()}catch(e){toast(e.message,true)}}
function detailAction(action,encoded){closeModal();if(action==='edit')editSite(encoded);if(action==='test')testSite(encoded);if(action==='install')installSite(encoded)}
function renderDetail(){const s=sites.find(x=>x.name===detailName);if(!s){closeModal();return}const previousLog=q('#detailBody .loglist'),followLog=!previousLog||previousLog.scrollHeight-previousLog.scrollTop-previousLog.clientHeight<40,j=s.job||{},running=s.status==='running'||j.status==='running',pc=Math.max(0,Math.min(100,Number(j.percent||(s.status==='success'?100:0)))),logs=Array.isArray(j.logs)?j.logs:[],history=s.history||[],bytes=j.bytesTotal?formatBytes(j.bytesCompleted)+' / '+formatBytes(j.bytesTotal):'—',encoded=encodeURIComponent(s.name);q('#detailTitle').textContent=s.domain;q('#detailMeta').textContent=(s.connection?.host||'')+' · '+(s.connection?.remotePath||'');q('#detailBody').innerHTML=`<section class="section"><div class="jobbox"><div class="jobtop"><div><h3>${esc(j.message||statusLabel(s.status))}</h3><p>${esc(j.current||s.lastError||'')}</p></div><span class="badge ${esc(s.status||'ready')}">${statusLabel(s.status)}</span></div><div class="jobmetrics"><div class="jobmetric"><span>Thời gian</span><b>${formatDuration(j.elapsedSeconds||0)}</b></div><div class="jobmetric"><span>Dữ liệu tải</span><b>${bytes}</b></div><div class="jobmetric"><span>Tín hiệu cuối</span><b>${formatDuration(j.idleSeconds||0)} trước</b></div></div><div class="progresswrap"><div class="progressline"><span style="width:${pc}%"></span></div><span class="progressnum">${pc}%</span></div>${j.current?`<div class="currentfile"><strong>Đang xử lý:</strong> ${esc(j.current)}</div>`:''}</div></section><section class="section"><h3 class="sectiontitle">Log gần nhất</h3><div class="loglist" aria-live="polite">${logs.length?logs.slice(-30).map(line=>`<div class="logitem">${esc(line)}</div>`).join(''):'<div class="logitem">Chưa có log.</div>'}</div></section><section class="section"><h3 class="sectiontitle">Thao tác</h3><div class="detailactions"><button class="btn" ${running||s.status==='success'?'disabled':''} onclick="detailAction('edit','${encoded}')">Sửa</button><button class="btn" ${running||s.status==='success'?'disabled':''} onclick="detailAction('test','${encoded}')">Kiểm tra FTP</button><button class="btn primary" ${running||s.status==='success'?'disabled':''} onclick="detailAction('install','${encoded}')">${s.status==='error'?'Thử lại':'Cài ngay'}</button><button class="btn danger" ${running?'disabled':''} onclick="deleteSite('${encoded}')">Xóa khỏi OneClick</button></div></section><section class="section"><h3 class="sectiontitle">Lịch sử</h3><div class="history">${history.length?history.map(h=>`<div class="historyitem"><i class="historydot ${esc(h.status)}"></i><strong>${esc(h.message)}</strong><time>${dateText(h.createdAt)}</time></div>`).join(''):'<div class="historyitem">Chưa có lịch sử.</div>'}</div></section>`;const nextLog=q('#detailBody .loglist');if(followLog&&nextLog)nextLog.scrollTop=nextLog.scrollHeight}
function showDetail(encoded){detailName=decodeURIComponent(encoded);renderDetail();if(!detailName)return;q('#overlay').className='overlay show';q('#detailModal').className='modal show';clearTimeout(poll);refresh()}
refresh();
</script>
</body>
</html>'''
