// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {datastore} from '../models';
import {project} from '../models';
import {vm} from '../models';
import {backup} from '../models';
import {cloudflare} from '../models';
import {database} from '../models';
import {installer} from '../models';
import {recoverytool} from '../models';
import {state} from '../models';
import {recovery} from '../models';
import {runtimeenv} from '../models';
import {tunnel} from '../models';
import {sourceeditor} from '../models';
import {readiness} from '../models';

export function ConfigureDataStorage(arg1:string):Promise<datastore.Result>;

export function CopyWebsite(arg1:project.CopyRequest):Promise<project.CopyResult>;

export function CreateEnvironment(arg1:vm.Request):Promise<vm.Result>;

export function CreateProjectBackup(arg1:string):Promise<backup.Result>;

export function DetectProjectDirectory(arg1:string):Promise<project.Info>;

export function DiscoverProjectDirectories():Promise<Array<project.Info>>;

export function GetCloudflareConnection():Promise<cloudflare.ConnectionStatus>;

export function GetCloudflareConnections():Promise<Array<cloudflare.ConnectionStatus>>;

export function GetCopyPlan(arg1:project.CopyRequest):Promise<project.CopyPlan>;

export function GetDataStorageStatus():Promise<datastore.Status>;

export function GetDatabasePlan(arg1:database.Request):Promise<database.Plan>;

export function GetDependencyPlan(arg1:string):Promise<installer.Plan>;

export function GetEnvironmentPlan(arg1:vm.Request):Promise<vm.Plan>;

export function GetLegacyRecoveryImportPlan(arg1:string):Promise<recoverytool.ImportPlan>;

export function GetProjectDataStatus(arg1:string):Promise<backup.Status>;

export function GetProjects():Promise<state.Snapshot>;

export function GetRecoveryBackupPlan(arg1:string):Promise<recovery.BackupPlan>;

export function GetRecoveryProjects():Promise<recovery.Snapshot>;

export function GetRecoveryToolStatus():Promise<recoverytool.Status>;

export function GetRuntimePlan(arg1:runtimeenv.Request):Promise<runtimeenv.Plan>;

export function GetTunnelPlan(arg1:tunnel.Request):Promise<tunnel.Plan>;

export function ImportDatabase(arg1:database.Request):Promise<database.Result>;

export function ImportLegacyRecoveryData(arg1:string):Promise<recoverytool.ImportResult>;

export function InstallRuntime(arg1:runtimeenv.Request):Promise<runtimeenv.Result>;

export function ListProjectSource(arg1:string,arg2:string):Promise<sourceeditor.Listing>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenProjectBackupFolder(arg1:string):Promise<void>;

export function OpenProjectSource(arg1:string):Promise<void>;

export function OpenRecoveryFolder(arg1:string):Promise<void>;

export function PrepareRecoveryTool():Promise<recoverytool.Status>;

export function ReadProjectSourceFile(arg1:string,arg2:string):Promise<sourceeditor.File>;

export function RecreateEnvironment(arg1:vm.Request):Promise<vm.Result>;

export function RemoveCloudflareConnection(arg1:string):Promise<void>;

export function RemoveRecoveryProject(arg1:string):Promise<void>;

export function RunDependencyAction(arg1:string):Promise<installer.Result>;

export function RunReadinessChecks():Promise<readiness.Report>;

export function RunRecoveryBackup(arg1:string):Promise<recovery.BackupResult>;

export function SaveCloudflareConnection(arg1:cloudflare.ConnectionInput):Promise<cloudflare.ConnectionStatus>;

export function SaveProjectConfiguration(arg1:state.ProjectInput):Promise<state.ProjectRecord>;

export function SaveProjectSourceFile(arg1:sourceeditor.SaveRequest):Promise<sourceeditor.SaveResult>;

export function SaveRecoveryProject(arg1:recovery.ProjectInput):Promise<recovery.Project>;

export function SelectDataStorageDirectory():Promise<string>;

export function SelectDatabaseFile(arg1:string):Promise<string>;

export function SelectLegacyRecoveryDirectory():Promise<string>;

export function SelectProjectDirectory():Promise<string>;

export function StartNamedTunnel(arg1:tunnel.Request):Promise<tunnel.Result>;

export function StartRecoveryTool():Promise<recoverytool.Status>;

export function StopNamedTunnel(arg1:tunnel.Request):Promise<tunnel.Result>;

export function TestRecoveryConnection(arg1:string):Promise<recovery.ConnectionResult>;
