// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureDataStorage(arg1) {
  return window['go']['main']['App']['ConfigureDataStorage'](arg1);
}

export function CopyWebsite(arg1) {
  return window['go']['main']['App']['CopyWebsite'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['main']['App']['CreateEnvironment'](arg1);
}

export function CreateProjectBackup(arg1) {
  return window['go']['main']['App']['CreateProjectBackup'](arg1);
}

export function DetectProjectDirectory(arg1) {
  return window['go']['main']['App']['DetectProjectDirectory'](arg1);
}

export function DiscoverProjectDirectories() {
  return window['go']['main']['App']['DiscoverProjectDirectories']();
}

export function GetCloudflareConnection() {
  return window['go']['main']['App']['GetCloudflareConnection']();
}

export function GetCloudflareConnections() {
  return window['go']['main']['App']['GetCloudflareConnections']();
}

export function GetCopyPlan(arg1) {
  return window['go']['main']['App']['GetCopyPlan'](arg1);
}

export function GetDataStorageStatus() {
  return window['go']['main']['App']['GetDataStorageStatus']();
}

export function GetDatabasePlan(arg1) {
  return window['go']['main']['App']['GetDatabasePlan'](arg1);
}

export function GetDependencyPlan(arg1) {
  return window['go']['main']['App']['GetDependencyPlan'](arg1);
}

export function GetEnvironmentPlan(arg1) {
  return window['go']['main']['App']['GetEnvironmentPlan'](arg1);
}

export function GetLegacyRecoveryImportPlan(arg1) {
  return window['go']['main']['App']['GetLegacyRecoveryImportPlan'](arg1);
}

export function GetProjectDataStatus(arg1) {
  return window['go']['main']['App']['GetProjectDataStatus'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetRecoveryBackupPlan(arg1) {
  return window['go']['main']['App']['GetRecoveryBackupPlan'](arg1);
}

export function GetRecoveryProjects() {
  return window['go']['main']['App']['GetRecoveryProjects']();
}

export function GetRecoveryToolStatus() {
  return window['go']['main']['App']['GetRecoveryToolStatus']();
}

export function GetRuntimePlan(arg1) {
  return window['go']['main']['App']['GetRuntimePlan'](arg1);
}

export function GetTunnelPlan(arg1) {
  return window['go']['main']['App']['GetTunnelPlan'](arg1);
}

export function ImportDatabase(arg1) {
  return window['go']['main']['App']['ImportDatabase'](arg1);
}

export function ImportLegacyRecoveryData(arg1) {
  return window['go']['main']['App']['ImportLegacyRecoveryData'](arg1);
}

export function InstallRuntime(arg1) {
  return window['go']['main']['App']['InstallRuntime'](arg1);
}

export function ListProjectSource(arg1, arg2) {
  return window['go']['main']['App']['ListProjectSource'](arg1, arg2);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenProjectBackupFolder(arg1) {
  return window['go']['main']['App']['OpenProjectBackupFolder'](arg1);
}

export function OpenProjectSource(arg1) {
  return window['go']['main']['App']['OpenProjectSource'](arg1);
}

export function OpenRecoveryFolder(arg1) {
  return window['go']['main']['App']['OpenRecoveryFolder'](arg1);
}

export function PrepareRecoveryTool() {
  return window['go']['main']['App']['PrepareRecoveryTool']();
}

export function ReadProjectSourceFile(arg1, arg2) {
  return window['go']['main']['App']['ReadProjectSourceFile'](arg1, arg2);
}

export function RecreateEnvironment(arg1) {
  return window['go']['main']['App']['RecreateEnvironment'](arg1);
}

export function RemoveCloudflareConnection(arg1) {
  return window['go']['main']['App']['RemoveCloudflareConnection'](arg1);
}

export function RemoveRecoveryProject(arg1) {
  return window['go']['main']['App']['RemoveRecoveryProject'](arg1);
}

export function RunDependencyAction(arg1) {
  return window['go']['main']['App']['RunDependencyAction'](arg1);
}

export function RunReadinessChecks() {
  return window['go']['main']['App']['RunReadinessChecks']();
}

export function RunRecoveryBackup(arg1) {
  return window['go']['main']['App']['RunRecoveryBackup'](arg1);
}

export function SaveCloudflareConnection(arg1) {
  return window['go']['main']['App']['SaveCloudflareConnection'](arg1);
}

export function SaveProjectConfiguration(arg1) {
  return window['go']['main']['App']['SaveProjectConfiguration'](arg1);
}

export function SaveProjectSourceFile(arg1) {
  return window['go']['main']['App']['SaveProjectSourceFile'](arg1);
}

export function SaveRecoveryProject(arg1) {
  return window['go']['main']['App']['SaveRecoveryProject'](arg1);
}

export function SelectDataStorageDirectory() {
  return window['go']['main']['App']['SelectDataStorageDirectory']();
}

export function SelectDatabaseFile(arg1) {
  return window['go']['main']['App']['SelectDatabaseFile'](arg1);
}

export function SelectLegacyRecoveryDirectory() {
  return window['go']['main']['App']['SelectLegacyRecoveryDirectory']();
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function StartNamedTunnel(arg1) {
  return window['go']['main']['App']['StartNamedTunnel'](arg1);
}

export function StartRecoveryTool() {
  return window['go']['main']['App']['StartRecoveryTool']();
}

export function StopNamedTunnel(arg1) {
  return window['go']['main']['App']['StopNamedTunnel'](arg1);
}

export function TestRecoveryConnection(arg1) {
  return window['go']['main']['App']['TestRecoveryConnection'](arg1);
}
